FasterXML/jackson-dataformat-xml

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/stream/XmlGeneratorTest.java

Currently only writeRaw methods are supported.
Default implementation for writeRawValue from GeneratorBase redirects call to writeRaw.
This lead to element name to be ignored which in order leads to invalid XML.
This change will allow to write 'writeRawValue' code in the same fashion as Json one and generating valid XML

Adding writeRawValue method support to ToXmlGenerator.

---

src/main/java/com/fasterxml/jackson/dataformat/xml/XmlMapper.java
src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlSerializerProvider.java
src/test/java/com/fasterxml/jackson/dataformat/xml/VersionInfoTest.java

Issue#233 XmlMapper.copy() doesn't properly copy internal configurations

---

src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlTokenStream.java
src/test/java/com/fasterxml/jackson/dataformat/xml/deser/TestStringValues162.java

Fix for #162 (XML Empty tag to Empty string)

---

README.md

As of recent versions of Android the current Android-specific instructions in the README are broken. 
If you declare an explicit dependency on the Stax API the Android build tools will fail your build when you attempt to package a non-debuggable version of your app (necessary for publishing to the Play Store). This issue was reported [here](https://github.com/FasterXML/jackson-dataformat-xml/issues/142) and [here](https://github.com/FasterXML/jackson-dataformat-xml/issues/238).
There are (extremely hacky) [workarounds](https://stackoverflow.com/questions/31360025/using-jackson-dataformat-xml-on-android) that exist, but others have reported unresolved problems with them.
I would advocate explicitly declaring that Android usage is currently unsupported since:
* In the comments to the …

Amending Android usage notes.

---

README.md

A previous commit changed the URL for the Woodstox project, but not it's Maven coordinates. This fixes that.

fix wrong Maven coordinates for Woodstox

---

src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlTokenStream.java

I found that small change to make a huge performance difference in some scenarios. In one case of processing a sample XML file of about 4 MB into POJOs, the CPU time sank by a factor of 100, from around 5–10 seconds to a few tens of milliseconds on a recent MacBook Pro with Azul OpenJDK 8.

Replaced slow string concatenation with faster StringBuilder

---

src/test/java/com/fasterxml/jackson/dataformat/xml/deser/XsiNil354Test.java

XML containing a nested field with `xsi:nil="true"` causes following fields to be deserialized at the wrong hierarchy. I've added a unit test to demonstrate this incorrect behavior.
This appears to be a new bug in 2.10.0 as a result of https://github.com/FasterXML/jackson-dataformat-xml/commit/4938036087bed3ebdfaf6c98db14d269179c30a8

XML containing xsi:nil is improperly parsed

---

README.md

JAXB annotation module was moved to jackson-modules-base.

Update JAXB link in README.md

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerialization.java

I'm not necessarily a big fan of having this `xsi:nil` in the middle of the code, let me know if you think I should extract it to a constant / use an existing constant (I looked for one but didn't find any).

Part of #360, use xsi:nil for null value with non-pretty writer

---

README.md

By the way: Thank you for providing Jackson. 👍

Small update of the known limitations section of the README

---

src/main/java/com/fasterxml/jackson/dataformat/xml/deser/WrapperHandlingDeserializer.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/ListDeserializationTest.java

WrapperHandlingDeserializer does not add aliases for unwrapped properties to the set of unwrapped names,
causing deserialization of unwrapped lists using aliases to fail.
This has the slightly strange behavior that if you mix aliases you'll end up with the latter sequence.
Ex `<val>1</val><alias>2</alias>` will deserialize to `[2]` instead of `[1,2]`

Fix JsonAlias with unwrapped lists

---

src/test/java/com/fasterxml/jackson/dataformat/xml/failing/Issue491NoArgCtorDeserRegressionTest.java

Add test to reproduce the `no default no-arg ctor` regression in #491. (This PR supersedes FasterXML/jackson-integration-tests#10.)

Add test to reproduce the `no default no-arg ctor` regression in #491

---

src/test/java/com/fasterxml/jackson/dataformat/xml/jaxb/AttributesWithJAXBTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/jaxb/WithJAXBAnnotationsTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/Issue101UnwrappedListAttributesTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/ListAnnotationSharingTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/misc/UnwrappingWithXMLTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestIndentation.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestJDKSerializability.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerializationAttr.java

Fixed eight flaky tests by using the annotation @JsonPropertyOrder and configuring map to guarantee the order. A ﬂaky test is an analysis of web application code that fails to produce the same result each time the same analysis is run. Flaky tests are detected by nondex (https://github.com/TestingResearchIllinois/NonDex) which is tool developped by the research group led by professor Darko at UIUC.
1. com.fasterxml.jackson.dataformat.xml.jaxb.AttributesWithJAXBTest#testTwoAttributes
2. com.fasterxml.jackson.dataformat.xml.jaxb.WithJAXBAnnotationsTest#testPersonAsXml
3. com.fasterxml.jackson.dataformat.xml.lists.ListAnnotationSharingTest#testAnnotationSharing
4. com.fasterxml.jackson.dataformat.xml.misc.UnwrappingWithXMLTest#testUnwrappingWithAttribute
5. …

Fix 8 Flaky Tests

---

src/test/java/com/fasterxml/jackson/dataformat/xml/jaxb/ElementWrapperTest.java

`testNoElementWrapper` is flaky since the order of names is nondeterministic. I fixed it by adding all possibilities of the orders.

fix a flaky test

---

src/test/java/com/fasterxml/jackson/dataformat/xml/deser/NumberDeserWithXMLTest.java

I was having a look to see if the code in this module needed to change to best support the fast double parser in jackson-core and saw that there weren't many tests for doubles/floats.
Java 17 CI build fails but that looks like a pre-existing issue.

add tests for doubles/floats

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/misc/XmlTextTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/stream/XmlGeneratorTest.java

Support unwrapping in `@JsonRawValue` serialization

---

src/main/java/com/fasterxml/jackson/dataformat/xml/XmlFactory.java
src/main/java/com/fasterxml/jackson/dataformat/xml/XmlFactoryBuilder.java
src/main/java/com/fasterxml/jackson/dataformat/xml/XmlMapper.java
src/main/java/com/fasterxml/jackson/dataformat/xml/XmlTagProcessor.java
src/main/java/com/fasterxml/jackson/dataformat/xml/XmlTagProcessors.java
src/main/java/com/fasterxml/jackson/dataformat/xml/deser/FromXmlParser.java
src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlTokenStream.java
src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/misc/TagEscapeTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/stream/XmlTokenStreamTest.java

This commit introduces the `PROCESS_ESCAPED_MALFORMED_TAGS` and
`ESCAPE_MALFORMED_TAGS` features that control whether invalid
tag names will be escaped with an attribute.
fixes #523
fixes #524

Fix generating invalid XML tag names

---

src/main/java/com/fasterxml/jackson/dataformat/xml/util/StaxUtil.java

* relates to https://github.com/FasterXML/jackson-dataformat-xml/issues/533
* I don't build Android apps but the original description in #533 seems to indicate that a NoSuchMethodError happens because stax-api jar does not have newFactory methods.

fail over to factory newInstance for Android support

---

src/main/java/com/fasterxml/jackson/dataformat/xml/deser/FromXmlParser.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/StringListRoundtripTest.java

Possible fix for https://github.com/FasterXML/jackson-dataformat-xml/issues/584.
As a note, empty and `null` string values in `Map`s were correctly handled even before the change (although requiring the map itself to be wrapped in a POJO). I included a test anyways.

Fix handling of null values in string Arrays and Collections

---

src/test/java/com/fasterxml/jackson/dataformat/xml/lists/StringListRoundtripTest.java

Following up on https://github.com/FasterXML/jackson-dataformat-xml/pull/585 with additional tests as suggested. I've added tests for POJOs with a string array or with a list, both are behaving as expected. I also added a test for a simple POJO with just plain string properties to be extra sure nothing breaks.
Regarding [this comment](https://github.com/FasterXML/jackson-dataformat-xml/pull/585#discussion_r1141076795):
> Ok, this explicit comment makes me nervous: it specifically spells out that when asking from nextTextValue(), empty element should not be coerced into null
I was unsure about that comment too, but it looks like that particular token switch case `XmlTokenStream.XML_END_ELEMENT` only occurs for `null` string values (when `xsi:nil` writing and processing is enabled). The …

Additional tests for string arrays and collections

---

src/main/java/com/fasterxml/jackson/dataformat/xml/util/TypeUtil.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/ListSerializationTest.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/IterationType302Test.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/Jdk8StreamSerialization302Test.java

resolves below issues
- #302
- #329
- #148
- modified related test

Support serialization of `Iterator` and `Stream`

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlSerializerProvider.java
src/main/java/com/fasterxml/jackson/dataformat/xml/util/TypeUtil.java

Make use of new `IterationType` class added by https://github.com/FasterXML/jackson-databind/issues/3950

Use `IterationType` in `TypeUtil`

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/dos/CyclicDataSerTest.java

relates to https://github.com/FasterXML/jackson-core/pull/1055
For deserialization, we rely on Woodstox (or other XML Stream Parser impl) to police the max depth. See https://github.com/FasterXML/jackson-dataformat-xml#usage for how you can configure Woodstox parser (and set the [P_MAX_ELEMENT_DEPTH](http://fasterxml.github.io/woodstox/javadoc/5.0/com/ctc/wstx/api/WstxInputProperties.html#P_MAX_ELEMENT_DEPTH) - default 1000).
Woodstox does not appear to support such a feature for XML writing so jackson-dataformat-xml needs it own code.

police against issues serializing cyclic data

---

src/main/java/com/fasterxml/jackson/dataformat/xml/deser/FromXmlParser.java
src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java

need to close the IOContext now (part of the BufferRecycler changes in v2.16)

close IOContext

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlBeanSerializerBase.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerializationWithFilter.java

In serializeFields() of XmlBeanSerializerBase, setNextIsUnwrapped(true) is executed in L.200-203, and setNextIsUnwrapped(false) is executed in L.215-219.
However, in serializeFieldsFiltered(), setNextIsUnwrapped(true) is executed in L.282-285, but there is no corresponding setNextIsUnwrapped(false).

Fix mismatch in setNextIsUnwrapped(true/false) in XmlBeanSerializerBase#serializeFieldsFiltered()

---

release-notes/CREDITS-2.x
release-notes/VERSION-2.x
src/main/java/com/fasterxml/jackson/dataformat/xml/ser/ToXmlGenerator.java
src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerialization.java

This PR adds a `ToXmlGenerator.Feature` to use XML Schema-compatible representation for floating-point infinity.
Fixes #643.

Fix #643: Add `ToXmlGenerator.Feature` or allowing XML Schema/JAXB compatible Infinity representation

---

release-notes/CREDITS-2.x
release-notes/VERSION-2.x
src/main/java/com/fasterxml/jackson/dataformat/xml/util/TypeUtil.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/IterableCollectionBuilder646Test.java

Added failing test and fix or issue #646

Added fix for iterable collection builder methods not treating iterable as a collection

---

pom.xml

We are starting to follow `databind` module's test structure and this is what databind module used to have.
We need current change for `..../records/failing` test directory
Note : Ironically databind module went even further with recent [failing test handling improvement ](https://github.com/FasterXML/jackson-databind/pull/4696), but we need to upgrade to JUnit 5 to achieve that.

Modify `surefire plugin` failing test scope 

---

release-notes/VERSION-2.x
src/main/java/com/fasterxml/jackson/dataformat/xml/JacksonXmlModule.java
src/main/java/com/fasterxml/jackson/dataformat/xml/XmlMapper.java

Implements a feature to address #678.

Fix #678: allow configuring custom SerializerFactory via JacksonXmlModule

---

src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerializationWithFilter.java

Due to the non-deterministic behavior of serialized XML output, the order of items in the class can vary. This may lead to an AssertionError when comparing an item object with its expected value.
The example below shows a failure under NonDex on [line 54](https://github.com/FasterXML/jackson-dataformat-xml/blob/21cc003e2d061efc10e3bf34c90e890887dbc36d/src/test/java/com/fasterxml/jackson/dataformat/xml/ser/TestSerializationWithFilter.java#L54)
<details>
<summary>Click on to see more details on the error message when running each test</summary>
```
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] ------------------------------------------------------- …
```

Test Fix: Resolve unintended test failures caused by non-deterministic ordering of elements in the serialized XML output

---

src/main/java/tools/jackson/dataformat/xml/XmlMapper.java
src/main/java/tools/jackson/dataformat/xml/ser/UnwrappingXmlBeanSerializer.java
src/main/java/tools/jackson/dataformat/xml/ser/XmlBeanPropertyWriter.java
src/main/java/tools/jackson/dataformat/xml/ser/XmlBeanSerializer.java
src/main/java/tools/jackson/dataformat/xml/ser/XmlBeanSerializerBase.java
src/main/java/tools/jackson/dataformat/xml/ser/XmlSerializationContext.java
src/main/java/tools/jackson/dataformat/xml/ser/XmlSerializationContexts.java
src/test/java/tools/jackson/dataformat/xml/ser/CustomSerializerTest.java
src/test/java/tools/jackson/dataformat/xml/ser/JsonAppend578Test.java
src/test/java/tools/jackson/dataformat/xml/ser/TestSerializationWithFilter.java
src/test/java/tools/jackson/dataformat/xml/ser/TestSerializerCustom.java

See https://github.com/FasterXML/jackson-databind/issues/3043 for details

Changes wrt databind/3043 (`SerializerProvider` -> `SerializationContext`)

---

src/test/java/tools/jackson/dataformat/xml/deser/EmptyWithScalarsTest.java

Resolves failing tests affected by https://github.com/FasterXML/jackson-databind/issues/4858

[`master`] fix failing tests after `FAIL_ON_NULL_FOR_PRIMITIVES` to `true` [databind#4890]

---

src/test/java/com/fasterxml/jackson/dataformat/xml/deser/NumberDeserWithXMLTest.java

* based on https://github.com/FasterXML/jackson-databind/issues/4917
* I couldn't find an existing case in this repo that matched that test
* I think it is useful to add to the regression coverage

add extra number test

---

src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlBeanSerializer.java
src/main/java/com/fasterxml/jackson/dataformat/xml/ser/XmlBeanSerializerBase.java

No need for separate handling of any-getter now.
Resolves #718

Remove `_anyGetterWriter` extended usage

---

release-notes/VERSION
src/main/java/tools/jackson/dataformat/xml/XmlWriteFeature.java
src/main/java/tools/jackson/dataformat/xml/annotation/JacksonXmlRootElement.java
src/test/java/tools/jackson/dataformat/xml/misc/RootNameTest.java
src/test/java/tools/jackson/dataformat/xml/stream/XmlGeneratorTest.java
src/test/java/tools/jackson/dataformat/xml/stream/XmlParserTest.java

Change `XmlWriteFeature` defaults

---

src/main/java/tools/jackson/dataformat/xml/XmlFactory.java
src/main/java/tools/jackson/dataformat/xml/XmlFactoryBuilder.java
src/main/java/tools/jackson/dataformat/xml/XmlMapper.java
src/main/java/tools/jackson/dataformat/xml/deser/FromXmlParser.java
src/test/java/tools/jackson/dataformat/xml/XmlMapperTest.java

* https://github.com/FasterXML/jackson-databind/pull/5004 is merged
* looks like there are some more config changes coming
@cowtowncoder will you notify me when the config changes are finished so that I can update this PR

Support `configureForJackson2()` with `XmlMapper`

---

src/test-jdk17/java/com/fasterxml/jackson/dataformat/xml/jdk17/Java17CollectionsTest.java
src/test-jdk17/java/com/fasterxml/jackson/dataformat/xml/records/failing/XmlWrapperRecord517Test.java
src/test/java/com/fasterxml/jackson/dataformat/xml/lists/StringListRoundtripTest.java

This is a bug fix because tests that use the org.junit.Test annotation no longer seem to run.
See #736

fix test imports (jupiter)

---

src/test/java/tools/jackson/dataformat/xml/tofix/records/XmlRecordDeser734Test.java

@cowtowncoder this seems to reproduce the issue in #734 
I targeted master because of the build issues in 2.19 branch - #737 (etc)
When enabled, I get
```
[ERROR] Errors: 
[ERROR]   XmlRecordDeser734Test.testDeser:25 » InvalidDefinition Invalid definition for property '' (of type `tools.jackson.dataformat.xml.tofix.records.XmlRecordDeser734Test$Amount`): Could not find creator property with name '' (known Creator properties: [value, Ccy])
at [Source: (String)"<Amt Ccy="EUR">1</Amt>"; line: 1, column: 1]
```

add test for issue 734 (disabled)
